[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefix=./"

# Serverless Functions configuration
[functions]
  # Point to the directory where the serverless functions are located
  directory = ".netlify/functions-internal/"
  # Node.js version for serverless functions
  node_bundler = "esbuild"
  # Enable Node.js compatibility
  external_node_modules = ["@resend/resend"]

# Handle client-side routing with proper SSR support
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200
  force = true

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Static assets
[[redirects]]
  from = "/_astro/*"
  to = "/_astro/:splat"
  status = 200
  force = true

# Other static files
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200
  force = true
  conditions = {Language = ["en", "es"]}

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self' https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com;"