[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefix=./"

# Serverless Functions configuration
[functions]
  # Point to the directory where the serverless functions are located
  directory = ".netlify/functions-internal/"
  # Node.js version for serverless functions
  node_bundler = "esbuild"
  # Enable Node.js compatibility
  external_node_modules = ["@resend/resend"]

# Handle all routes through the SSR function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200

# Handle static files
[[redirects]]
  from = "/_astro/*"
  to = "/_astro/:splat"
  status = 200

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Ensure proper MIME types for assets
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"