[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefix=./"
  NODE_OPTIONS = "--experimental-vm-modules"
  ASTRO_NETLIFY_ADAPTER_MODE = "static"

# Configuración para el archivo manifest
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=600"

# Configuración para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuración de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://cdnjs.cloudflare.com https://www.unpkg.com;
      style-src 'self' 'unsafe-inline' https://rsms.me https://fonts.googleapis.com;
      img-src 'self' data: https: blob:;
      font-src 'self' https://rsms.me https://fonts.gstatic.com;
      connect-src 'self' https://rsms.me https://fonts.googleapis.com https://fonts.gstatic.com https://www.unpkg.com;
      worker-src 'self' blob:;
      frame-src 'self';
      worker-src 'self' blob:;
      child-src 'self' blob:;
      script-src-elem 'self' 'unsafe-inline' https://unpkg.com https://cdnjs.cloudflare.com https://www.unpkg.com;
      style-src-elem 'self' 'unsafe-inline' https://rsms.me https://fonts.googleapis.com;
      require-trusted-types-for 'script';
    """

# Redirecciones para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de encabezados para archivos específicos
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"